services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-config:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin