[tool.poetry]
name = "fastapi-app"
version = "0.1.0"
description = ""
authors = ["leokoike <leokoike@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "*"
pydantic = "*"
SQLAlchemy = "*"
asyncpg = "*"
uvicorn = "*"
cryptography = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
